
vocab:
  type: Vocab
  path:
    train: datasets/UIT-ViNewsOnSum.-dataset/train.json
    dev: datasets/UIT-ViNewsOnSum.-dataset/dev.json
    test: datasets/UIT-ViNewsOnSum.-dataset/test.json
  min_freq: 3
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: TextSumDataset
    path: datasets/UIT-ViNewsOnSum.-dataset/train.json
  dev:
    type: TextSumDataset
    path: datasets/UIT-ViNewsOnSum.-dataset/dev.json
  test: 
    type: TextSumDataset
    path: datasets/UIT-ViNewsOnSum.-dataset/test.json
  batch_size: 32
  num_workers: 16

model: 
  name: abstractiveRNN_UIT-ViNewsOnSum.
  architecture: abstractiveRNN
  rnn_type: 'gru'
  embz_size: 256
  hidden_size: 512
  batch_size: 32
  max_tgt_len: 25
  attention_type: 'luong'
  tied_weight_type: 'three_way'
  pre_trained_vector_type: None
  padding_idx: 0
  num_layers: 1
  encoder_drop: [0.2, 0.3]
  decoder_drop: [0.2, 0.3]
  bidirectional: true
  bias: false
  teacher_forcing: true
  num_layers: 1
  device: cuda
  lr: 1e-3
  epochs: 5

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.5
  warmup: 1000
  patience: 5
  score: rouge-L

task: TextSumTask