vocab:
  type: Vocab
  path:
    train: datasets/UIT-ViNewsOnSum-dataset/train.json
    dev: datasets/UIT-ViNewsOnSum-dataset/dev.json
    test: datasets/UIT-ViNewsOnSum-dataset/test.json
  min_freq: 3
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: TextSumDataset
    path: datasets/UIT-ViNewsOnSum-dataset/train.json
  dev:
    type: TextSumDataset
    path: datasets/UIT-ViNewsOnSum-dataset/dev.json
  test:
    type: TextSumDataset
    path: datasets/UIT-ViNewsOnSum-dataset/test.json
  batch_size: 32
  num_workers: 16

model:
  name: BiGRU_Model3layer_UIT-ViNewsOnSum
  architecture: BiGRU_Model
  d_model: 512
  encoder:
    layer_dim: 3
    input_dim: 512
    hidden_size: 512
    bidirectional: True
    dropout: 0.1
  decoder:
    layer_dim: 3
    input_dim: 512
    hidden_size: 512
    bidirectional: True
    dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.5
  warmup: 1000
  patience: 5
  score: rouge-L

task: TextSumTask