device: cuda

content_selector:
  config: configs/content_selector_VietNews.yaml
  checkpoint: checkpoints/content_selector/ContentSelector_VietNews/best_model.pth

pointer_generator:
  config: configs/Pointer_Generator_VietNews.yaml
  checkpoint: checkpoints/pointer_generator_VietNews/best_model.pth

inference:
  threshold: 0.2
  soft_coeff: 0.0
  coverage_beta: 10
  batch_size: 1
  output_dir: checkpoints/bottom_up_VietNews