
vocab:
  type: Vocab
  path:
    train: datasets/sample/train.json
    dev: datasets/sample/dev.json
    test: datasets/sample/test.json
  min_freq: 3
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: TextSumDataset
    path: C:\Users\DELL\ViPhoLM\ViPhoLM\datasets\sample\train.json
  dev:
    type: TextSumDataset
    path: C:\Users\DELL\ViPhoLM\ViPhoLM\datasets\sample\dev.json
  test:
    type: TextSumDataset
    path: C:\Users\DELL\ViPhoLM\ViPhoLM\datasets\sample\test.json
  batch_size: 2
  num_workers: 8

model:
  name: HATModel_UIT-ViNewsOnSum
  architecture: HATModel
  segment_len: 128
  hidden_size: 128
  max_segments: 64
  nhead: 2
  num_layers: 4
  encoder_layout:
    "0":
      sentence_encoder: true
      document_encoder: false
    "1":
      sentence_encoder: true
      document_encoder: true
    "2":
      sentence_encoder: true
      document_encoder: true
    "3":
      sentence_encoder: true
      document_encoder: true
  device: cpu

training:
  batch_size: 2
  learning_rate: 0.00001  # Giảm xuống 1e-4
  rl_weight: 0.5  # Trọng số cho RL loss
  checkpoint_path: "checkpoints"
  warmup: 1000
  patience: 5
  score: rouge-L

task: TextSumTask