vocab:
  type: Vocab
  path:
    train: datasets/Wikilingual-dataset/train.json
    dev: datasets/Wikilingual-dataset/dev.json
    test: datasets/Wikilingual-dataset/test.json
  min_freq: 3
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: TextSumDataset
    path: datasets/Wikilingual-dataset/train.json
  dev:
    type: TextSumDataset
    path: datasets/Wikilingual-dataset/dev.json
  test: 
    type: TextSumDataset
    path: datasets/Wikilingual-dataset/test.json
  batch_size: 32
  num_workers: 4

model:
  name: Hepos_Transformer_Wikilingual
  architecture: TransformerHeposModel
  d_model: 256
  n_layers: 4
  n_head: 8
  ffn_hidden: 1024
  drop_prob: 0.1
  max_len: 64
  encoder:
    d_model: 256
    n_head: 8
    ffn_hidden: 1024
    drop_prob: 0.1
    n_layers: 4
    max_len: 64
    device: cuda
  decoder:
    d_model: 256
    n_head: 8
    ffn_hidden: 1024
    drop_prob: 0.1
    n_layers: 4
    max_len: 64
    device: cuda
    stride: 2
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.0001
  lr_coverage: 0.0001
  warmup: 4000
  patience: 10
  score: rouge-L

task: TextSumTask