vocab:
  type: Vocab
  path:
    train: datasets/Vietnews-dataset/train.json
    dev: datasets/Vietnews-dataset/dev.json
    test: datasets/Wikilingual-dataset/test.json
  min_freq: 3
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>
  max_sentence_length: 60
  max_sentences: 20

dataset:
  train: 
    type: TextSumDatasetHierarchy
    path: datasets/Vietnews-dataset/train.json
  dev:
    type: TextSumDatasetHierarchy
    path: datasets/Vietnews-dataset/dev.json
  test: 
    type: TextSumDatasetHierarchy
    path: datasets/Vietnews-dataset/test.json
  batch_size: 16
  num_workers: 4


model:
  name: HierarchicalTransformer_Vietnews
  architecture: HierarchicalTransformer
  hidden_size: 512
  d_model: 512
  drop_prob: 0.1
  encoder:
    n_layers: 4
    n_head: 8
    hidden_size: 512
    ffn_hidden: 2048
    drop_prob: 0.1
  decoder:
    n_layers: 4
    n_head: 8
    hidden_size: 512
    ffn_hidden: 2048
    drop_prob: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.15
  lr_coverage: 0.15
  warmup: 1000
  patience: 5
  score: rouge-L

task: TextSumTaskHierarchy