vocab:
  type: Vocab
  path:
    train: datasets/Wikilingual-dataset-vn/train.json
    dev: datasets/Wikilingual-dataset-vn/dev.json
    test: datasets/Wikilingual-dataset-vn/test.json
  min_freq: 3
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: TextSumDataset
    path: datasets/Wikilingual-dataset-vn/train.json
  dev:
    type: TextSumDataset
    path: datasets/Wikilingual-dataset-vn/dev.json
  test: 
    type: TextSumDataset
    path: datasets/Wikilingual-dataset-vn/test.json
  batch_size: 16
  num_workers: 16

model:
  name: Testing_Wikilingual
  architecture: Testing
  hidden_size: 512
  n_layers: 6
  n_head: 8
  d_model: 512
  dim_feedforward: 2048
  ffn_hidden: 2048
  drop_prob: 0.1
  max_length: 2024
  encoder:
    hidden_size: 512
    n_head: 8
    dim_feedforward: 2048
    ffn_hidden: 2048
    drop_prob: 0.1
    n_layers: 6
    device: cuda
  decoder:
    hidden_size: 512
    n_head: 8
    dim_feedforward: 2048
    ffn_hidden: 2048
    drop_prob: 0.1
    n_layers: 6
    device: cuda
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.15   
  lr_coverage: 0.15
  warmup: 1000
  patience: 5
  score: rouge-L

task: TextSumTask